package com.fastpos.android.data.database

import java.sql.*
import java.util.Properties

/**
 * Stub Connection passed into transaction { conn -> } blocks when running in local SQLite mode.
 * The block receives this marker; insertAndGetIdSync detects isLocal() and uses localDb directly.
 */
object LocalMarkerConnection : Connection {

    private fun unsupported(): Nothing = throw UnsupportedOperationException("LocalMarkerConnection is a stub")

    override fun close() {}
    override fun isClosed(): Boolean = false
    override fun isValid(timeout: Int): Boolean = true
    override fun getAutoCommit(): Boolean = false
    override fun setAutoCommit(autoCommit: Boolean) {}
    override fun commit() {}
    override fun rollback() {}
    override fun rollback(savepoint: Savepoint?) {}
    override fun getMetaData(): DatabaseMetaData = unsupported()
    override fun isReadOnly(): Boolean = false
    override fun setReadOnly(readOnly: Boolean) {}
    override fun getCatalog(): String? = null
    override fun setCatalog(catalog: String?) {}
    override fun getTransactionIsolation(): Int = Connection.TRANSACTION_SERIALIZABLE
    override fun setTransactionIsolation(level: Int) {}
    override fun getWarnings(): SQLWarning? = null
    override fun clearWarnings() {}
    override fun getTypeMap(): MutableMap<String, Class<*>> = unsupported()
    override fun setTypeMap(map: MutableMap<String, Class<*>>?) {}
    override fun getHoldability(): Int = ResultSet.HOLD_CURSORS_OVER_COMMIT
    override fun setHoldability(holdability: Int) {}
    override fun createStatement(): Statement = unsupported()
    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement = unsupported()
    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement = unsupported()
    override fun prepareStatement(sql: String): PreparedStatement = unsupported()
    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement = unsupported()
    override fun prepareStatement(sql: String, columnIndexes: IntArray?): PreparedStatement = unsupported()
    override fun prepareStatement(sql: String, columnNames: Array<out String>?): PreparedStatement = unsupported()
    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement = unsupported()
    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): PreparedStatement = unsupported()
    override fun prepareCall(sql: String): CallableStatement = unsupported()
    override fun prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): CallableStatement = unsupported()
    override fun prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): CallableStatement = unsupported()
    override fun nativeSQL(sql: String): String = sql
    override fun setSavepoint(): Savepoint = unsupported()
    override fun setSavepoint(name: String?): Savepoint = unsupported()
    override fun releaseSavepoint(savepoint: Savepoint?) {}
    override fun createClob(): Clob = unsupported()
    override fun createBlob(): Blob = unsupported()
    override fun createNClob(): NClob = unsupported()
    override fun createSQLXML(): SQLXML = unsupported()
    override fun createArrayOf(typeName: String?, elements: Array<out Any>?): java.sql.Array = unsupported()
    override fun createStruct(typeName: String?, attributes: Array<out Any>?): Struct = unsupported()
    override fun getClientInfo(): Properties = Properties()
    override fun getClientInfo(name: String?): String? = null
    override fun setClientInfo(name: String?, value: String?) {}
    override fun setClientInfo(properties: Properties?) {}
    override fun <T : Any?> unwrap(iface: Class<T>): T = unsupported()
    override fun isWrapperFor(iface: Class<*>): Boolean = false
}
