package com.fastpos.android.ui.navigation

sealed class Screen(val route: String) {
    data object Splash    : Screen("splash")
    data object Setup     : Screen("setup")
    data object Login     : Screen("login")
    data object Dashboard : Screen("dashboard")
    data object Pos       : Screen("pos")
    data object Payment   : Screen("payment/{orderId}") {
        fun withOrder(orderId: Int) = "payment/$orderId"
    }
    data object Kitchen   : Screen("kitchen")
    data object Orders    : Screen("orders")
    data object More      : Screen("more")
    data object Shift     : Screen("shift")
    data object Settings  : Screen("settings")
    data object Reports   : Screen("reports")
    data object Products  : Screen("products")
    data object Customers : Screen("customers")
    data object Tables    : Screen("tables")
    data object Inventory  : Screen("inventory")
    data object Employees  : Screen("employees")
    data object Attendance   : Screen("attendance")
    data object Payroll      : Screen("payroll")
    data object RawMaterials : Screen("rawmaterials")
    data object Expenses     : Screen("expenses")
    data object Waiters      : Screen("waiters")
    data object Purchases    : Screen("purchases")
    data object Tax          : Screen("tax")
    data object Deals        : Screen("deals")
    data object Reservations : Screen("reservations")
    data object Delivery        : Screen("delivery")
    data object UserManagement  : Screen("usermanagement")
    data object Vouchers        : Screen("vouchers")
    data object CashDrawer      : Screen("cashdrawer")
    data object AuditLog        : Screen("auditlog")
    data object Waste           : Screen("waste")
    data object Suppliers       : Screen("suppliers")
    data object Recipes         : Screen("recipes")
    data object Modifiers       : Screen("modifiers")
    data object Branch          : Screen("branch")
    data object MessageLog      : Screen("messagelog")
    data object ProductLedger  : Screen("productledger")
    data object Activation     : Screen("activation")
    data object RaastQr        : Screen("raastqr")
    data object AccountLedger  : Screen("accountledger")
}
